import pandas as pd
df = pd.read_csv("sampledata.csv")
print(df)
print("--------------")
print("Usernames list :")
print(df["Usernames"])
print("----------")
print("Username: " , df["Usernames"][1] , "||" , "Password:", df["Passwords"][1])
print("--------------")
print("Usernames data in ascending order ")
print(df.sort_values("Usernames"))
print("---------------")
print("Passwords data in descending order ")
print(df.sort_values("Passwords", ascending = False))
